config/routes.rb
Logmaster5000::Application.routes.draw do
  root :to => 'Sessions#new'

  post 'sessions/new'

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  resources :labels do
    collection do
      get :get_names
    end
  end

  resources :logs do
    member do
      get :download
      get :resources
    end
  end

  resources :resources

end

app/models/label.rb
class Label < ActiveRecord::Base
	attr_accessible :name  
	has_and_belongs_to_many :logs

	validates :name, :presence => true, :exclusion => { :in => %w(new get_names), :message => "<strong>%{value}</strong> is reserved." }

	acts_as_url :name, :sync_url => true

  	def to_param
		url
	end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
	before_filter :authenticate_user!

	def index
		@label = Label.new
		@labels = Label.all

		respond_to do |format|
			format.html
			format.json { render :json => @labels }
	    end
	end

	def new
		@label = Label.new

		respond_to do |format|
			format.html
			format.js { render :layout => false }
	    end
	end

	def get_names
		@labels = Label.all

		respond_to do |format|
			format.json { render :json => { :tags => @labels.collect{|label| {:tag => label.name}} } }
	    end
	end

	def show
		@label = Label.find_by_url params[:id]
		if @label
			@logs = @label.logs
		else
			redirect_to labels_path, :notice => {:type=> 'error', :message=>'There was a problem locating your label.'}
		end
	end

	def create
		if params[:label]
			label = Label.create params[:label]

			if label.errors.any?
				redirect_to :back, :notice => {:type=> 'error', :message=>'There was a problem creating your new label.', :issues => { :type => "error", :messages => label.errors.full_messages } }
		    else
				redirect_to labels_path, :notice => {:type=> 'success', :message=>'Label has been created successfully.'}
			end
		else
			redirect_to :back, :notice => {:type=> 'error', :message=>'There was a problem creating your new label.'}
		end		
	end

	def edit
		@label = Label.find_by_url params[:id]

		respond_to do |format|
			format.html
			format.js { render :layout => false }
	    end
	end

	def update
		label = Label.find_by_url params[:id]

		if label.update_attributes params[:label]			
			redirect_to :back, :notice => {:type=> 'success', :message=>'Label has been updated successfully.'}
		else
			if label.errors.any?
				redirect_to :back, :notice => {:type=> 'error', :message=>'There was a problem updating your label.', :issues => { :type => "error", :messages => label.errors.full_messages } }
		    else
				redirect_to :back, :notice => {:type=> 'error', :message=>'There was an error updating label.'}
			end			
		end
	end

	def destroy
		label = Label.find_by_url params[:id]
		label.destroy
		redirect_to :back, :notice => {:type=> 'success', :message=>'Label has been deleted.'}
	end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<%= form_for @label, :html => { :style => "margin-bottom:0px" } do |f| %>    
    <div class="modal-header">
        <% if @label.id %>            
            <h3>Update Label <small><%= @label.name %></h3>
        <% else %>
            <h3>Add Label</h3>
        <% end %>        
    </div>
    <div class="modal-body">
        <div class="control-group">
            <%= f.label :name, :class => "control-label" %>
            <div class="controls">
                <%= f.text_field :name %>
            </div>          
        </div>
    </div>
    <div class="modal-footer">
        <button id="submit-btn" class="btn btn-primary pull-left">Save</button>
        <a href="<%= labels_path %>" class="btn pull-left" data-dismiss="modal">Cancel</a>
    </div>
<% end %>

app/views/labels/edit.js.erb
var inlineLabelFormModal = $('<div class="modal hide" id="inlineLabelFormModal"></div>');
inlineLabelFormModal.html("<%= escape_javascript(render 'form') %>");

$(".modal-header", inlineLabelFormModal).prepend('<button type="button" class="close" data-dismiss="modal">×</button>');

inlineLabelFormModal.modal('show');

$('#label_name', inlineLabelFormModal).focus();

app/views/labels/index.html.erb
<div class="page-header">	
  	<div class="btn-group pull-right span3">
  		<%= link_to 'add new label', new_label_path, :remote => true, :title => 'Add new label', :class => "label-modal-toggler btn btn-primary btn-small" %>
  	</div>
  	<h1>Available Labels</h1> 
</div>	

<div class="row">
	<div class="span12">
		<table class="table table-striped table-hover">
			<thead>
				<tr>
					<th>Name</th>
					<th width="25%"># of Logs</th>
					<th width="25%">Actions</th>
				</tr>
			</thead>
			<tbody>
			<% if @labels.size < 1 %>
				<tr>
					<td colspan="3">There are currently no labels files to list. Feel free to <%= link_to 'create one', new_label_path, :remote => true, :title => 'Add new label' %>.</td>
				</tr>
			<% else %>
				<% @labels.each do |label| %>
					<tr id="label_<%= label.id %>">
						<td><%= link_to label.name, label_path(label) %></td>
						<td><%= label.logs.size %></td>
						<td>
							<div class="btn-group">
								<%= link_to raw('<i class="icon-pencil"></i>'), edit_label_path(label), :remote => true, :title => 'Edit label', :class => "btn btn-small btn-link label-modal-toggler" %>
								<%= link_to raw('<i class="icon-trash"></i>'), label, :method => 'delete', :confirm => 'Are you sure you want to delete this label? This cannot be undone.', :title => 'Delete label', :class => "btn btn-small btn-link" %>
							</div>							
						</td>
					</tr>
				<% end %>
			<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/labels/new.js.erb
var inlineLabelFormModal = $('<div class="modal hide" id="inlineLabelFormModal"></div>');
inlineLabelFormModal.html("<%= escape_javascript(render 'form') %>");

$(".modal-header", inlineLabelFormModal).prepend('<button type="button" class="close" data-dismiss="modal">×</button>');

inlineLabelFormModal.modal('show');

$('#label_name', inlineLabelFormModal).focus();

app/views/labels/show.html.erb
<div class="page-header">	
	<div class="btn-group pull-right span3">
		<%= link_to raw('<i class="icon-pencil"></i> edit label'), edit_label_path(@label), :remote => true, :class => "modal-toggler btn btn-small" %>
  	</div>
  	<h1>Label Details <small><%= @label.name %></small></h1> 	
</div>

<%= render 'logs/loglisting' %>