config/routes.rb
Logmaster5000::Application.routes.draw do
  root :to => 'Sessions#new'

  post 'sessions/new'

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  resources :labels do
    collection do
      get :get_names
    end
  end

  resources :logs do
    member do
      get :download
      get :resources
    end
  end

  resources :resources

end

app/views/resources/_form.html.erb
<%= form_for @resource, :html => { :style => "margin-bottom:0px" } do |f| %>    
  <div class="modal-header">
    <% if @resource.id %>            
      <h3>Update Resource <small><%= @resource.name %></h3>
    <% else %>
      <h3>Add Resource</h3>
    <% end %>        
  </div>
  <div class="modal-body">
    <div class="control-group">
      <%= f.label :name, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :name, :class => "span4" %>
      </div>          
    </div>
    <div class="control-group">
      <%= f.label :regex, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :regex, :class => "span4" %>
      </div>          
    </div>
    <div class="control-group">
      <%= f.label :url, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :url, :class => "span4" %>
      </div>          
    </div>
  </div>
  <div class="modal-footer">
    <button id="submit-btn" class="btn btn-primary pull-left">Save</button>
    <a href="<%= resources_path %>" class="btn pull-left" data-dismiss="modal">Cancel</a>
  </div>
<% end %>

app/views/resources/edit.html.erb
<%= render 'form' %>

app/views/resources/edit.js.erb
var inlineResourceFormModal = $('<div class="modal hide" id="inlineResourceFormModal"></div>');
inlineResourceFormModal.html("<%= escape_javascript(render 'form') %>");

$(".modal-header", inlineResourceFormModal).prepend('<button type="button" class="close" data-dismiss="modal">×</button>');

inlineResourceFormModal.modal('show');

$('#resource_name', inlineResourceFormModal).focus();

app/views/resources/index.html.erb
<div class="page-header">	
  	<div class="btn-group pull-right span3">
  		<%= link_to 'add new resource', new_resource_path, :remote => true, :title => 'Add new resource', :class => "resource-modal-toggler btn btn-primary btn-small" %>
  	</div>
  	<h1>Available Resources</h1> 
</div>	

<div class="row">
	<div class="span12">
		<table class="table table-striped table-hover">
			<thead>
				<tr>
					<th>Name</th>
					<th width="25%">Actions</th>
				</tr>
			</thead>
			<tbody>
			<% if @resources.size < 1 %>
				<tr>
					<td colspan="2">There are currently no resources to list. Feel free to <%= link_to 'create one', new_resource_path, :remote => true, :title => 'Add new resource' %>.</td>
				</tr>
			<% else %>
				<% @resources.each do |resource| %>
					<tr id="resource_<%= resource.id %>">
						<td><%= link_to resource.name, resource_path(resource) %></td>
						<td>
							<div class="btn-group">
								<%= link_to raw('<i class="icon-pencil"></i>'), edit_resource_path(resource), :remote => true, :title => 'Edit resource', :class => "btn btn-small btn-link resource-modal-toggler" %>
								<%= link_to raw('<i class="icon-trash"></i>'), resource, :method => 'delete', :confirm => 'Are you sure you want to delete this resource? This cannot be undone.', :title => 'Delete resource', :class => "btn btn-small btn-link" %>
							</div>							
						</td>
					</tr>
				<% end %>
			<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/resources/new.html.erb
<%= render 'form' %>

app/views/resources/new.js.erb
var inlineResourceFormModal = $('<div class="modal hide" id="inlineResourceFormModal"></div>');
inlineResourceFormModal.html("<%= escape_javascript(render 'form') %>");

$(".modal-header", inlineResourceFormModal).prepend('<button type="button" class="close" data-dismiss="modal">×</button>');

inlineResourceFormModal.modal('show');

$('#resource_name', inlineResourceFormModal).focus();

app/views/resources/show.html.erb
<div class="page-header">	
	<div class="btn-group pull-right span3">
		<%= link_to raw('<i class="icon-pencil"></i> edit resource'), edit_resource_path(@resource), :remote => true, :class => "modal-toggler btn btn-small" %>
  	</div>
  	<h1>Resource Details</h1> 	
</div>

<dl class="dl-horizontal left-align">
	<dt>Name</dt>
	<dd><%= @resource.name %></dd>
	<dt>Regex</dt>
	<dd><%= @resource.regex %></dd>
	<dt>URL</dt>
	<dd><%= @resource.url %></dd>
</dl>