config/routes.rb
Logmaster5000::Application.routes.draw do
  root :to => 'Sessions#new'

  post 'sessions/new'

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  resources :labels do
    collection do
      get :get_names
    end
  end

  resources :logs do
    member do
      get :download
      get :resources
    end
  end

  resources :resources

end

app/models/log.rb
require 'carrierwave/orm/activerecord'
require 'fileutils'

class Log < ActiveRecord::Base
  attr_accessible :logfile, :entriesjson
  validates :logfile, presence: true
  mount_uploader :logfile, LogfileUploader
  mount_uploader :entriesjson, EntriesJsonUploader
  has_and_belongs_to_many :labels
end

app/controllers/logs_controller.rb
require 'yajl'

class LogsController < ApplicationController
	before_filter :authenticate_user!

	def index
		@log = Log.new
		@logs = Log.all		
	end

	def create		
		if params[:log]
			warnings = []

			log = Log.new
			log.logfile = params[:log][:logfile]	
			log.entriesjson = params[:log][:logfile]		
			log.save!

			if params[:hiddenTagList]
				log_labels = params[:hiddenTagList].split(',')
				log_labels.each do |label|
					new_label = Label.find_or_create_by_name(label)
					if new_label.errors.any?
						warnings.push(new_label.errors.full_messages)
					else
						log.labels << new_label
					end
				end
			end
			
			redirect_to :back, :notice => {:type=> 'success', :message=>'Log has been created successfully.', :issues => { :type => "warning", :messages => warnings.flatten} }
		else
			redirect_to :back, :notice => {:type=> 'error', :message=>'Please choose a log file for upload.'}
		end		
	end

	def destroy
		Log.destroy params[:id]
		redirect_to :back, :notice => {:type=> 'success', :message=>'Log has been deleted.'}
	end

	def download
		require 'mime/types'
		@log = Log.find params[:id]
		filename = @log.logfile.file.filename
		send_data @log.logfile.read, :type => MIME::Types.type_for(filename), :filename => File.basename(filename)
	end

	def edit
		@log = Log.find params[:id]
	end

	def new
		@log = Log.new
	end

	def resources
		@log = Log.find params[:id]
		@entries = Yajl::Parser.new.parse(@log.entriesjson.read)

		@resource_matches = _find_resource_matches(@entries["entries"])

		respond_to do |format|
			format.html
			format.js
			format.json { render :json => @matches }
	  end
	end

	def show
		@log = Log.find params[:id]

		@entries = {
			:data => @log.entriesjson.read
		}
		@entries[:json_hash] = Yajl::Parser.new.parse(@entries[:data])

		if @entries[:json_hash]["type"].nil?
			@entries[:json_hash]["type"] = ""
		end

		if @entries[:json_hash]["line_total"] == 0
			redirect_to :back, :notice => {:type => "error", :message => "It looks like the file that was specified was empty. Please choose a file below or upload a new one."}
		elsif @log.logfile.size.nil?
			redirect_to :back, :notice => {:type => "error", :message => "It looks like the file that was specified does not exist. Please choose a file below or upload a new one."}
		end

		@resource_matches = _find_resource_matches(@entries[:json_hash]["entries"])

		respond_to do |format|
			format.html
			format.json { render :json => @entries[:data] }
	  end
	end

	def update
		log = Log.find params[:id]		
		success = true
		warnings = []

		# Update log's labels.
		log.labels.clear
		if params[:hiddenTagList]
			log_labels = params[:hiddenTagList].split(',')
			log_labels.each do |label|
				new_label = Label.find_or_create_by_name(label)
				if new_label.errors.any?
					warnings.push new_label.errors.full_messages
				else
					log.labels << new_label
				end
			end
		end

		if params[:log]			
			log.logfile = params[:log][:logfile]
			log.entriesjson = params[:log][:logfile]

			if !log.save!
				success = false
			end
		end

		if success			
			redirect_to :back, :notice => {:type=> 'success', :message=>'Log has been updated successfully.', :issues => { :type => "warning", :messages => warnings.flatten} }
		else
			redirect_to :back, :notice => {:type=> 'error', :message=>'There was an error updating log.', :issues => { :type => "warning", :messages => warnings.flatten} }
		end	
	end

	def _find_resource_matches(log_entries)
		resource_matches = {}

		regexes = Resource.all.collect{|resource| {
			:resource => resource,
			:regex => Regexp.new(resource.regex)
		}}

		## Loop over each entry to see if we have a resource for it.
		log_entries.each do |entry|
			regexes.each do |regex|
					next unless regex[:regex] =~ entry["entrycontent"]
					if resource_matches.has_key?(regex[:resource].id)
						resource_matches[regex[:resource].id][:hits] += 1
					else
						resource_matches[regex[:resource].id] = {:resource => regex[:resource], :hits => entry["hits"]}
					end
			end
		end
		resource_matches
	end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= form_for @log, :html => { :style => "margin-bottom:0px" } do |f| %>    
    <div class="modal-header">
        <% if @log.id %>            
            <h3>Update Log <small><%= @log.logfile.file.filename %></h3>
        <% else %>
            <h3>Add Log</h3>
        <% end %>        
    </div>
    <div class="modal-body">
        <div class="control-group">
            <%= f.label :logfile, 'Log File', :class => "control-label" %>
            <div class="controls">
                <%= f.file_field :logfile %>
            </div>          
        </div>  
        <div class="control-group">
            <label class="control-label" for="labels">Labels</label>
            <div class="controls">
                <input type="text" name="labels" id="labels" placeholder="Add label..." class="span2" autocomplete="off" />
                <div class="hide"><%= @log.labels.map(&:name).join(',') %></div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button id="submit-btn" class="btn btn-primary pull-left">Save</button>
        <a href="<%= logs_path %>" class="btn pull-left" data-dismiss="modal">Cancel</a>
    </div>
<% end %>

app/views/logs/_loglabels.html.erb
<% if labels.size > 0 %>
	<i class="icon-tags"></i>&nbsp;
	<% labels.each do |label| %>
		<a href="<%= label_path(label) %>" class="label"><%= label.name %></a>
	<% end %>
<% end %>

app/views/logs/_loglisting.html.erb
<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th width="2%">ID</th>
			<th>File</th>
			<th width="25%">Size</th>
			<th width="25%">Log Actions</th>
		</tr>
	</thead>
	<tbody>
	<% if @logs.size < 1 %>
		<tr>
			<td colspan="4">There are currently no log files to list. Feel free to <%= link_to 'upload one', new_log_path, :remote => true %>.</td>
		</tr>
	<% else %>
		<% @logs.each do |log| %>
			<tr id="log_<%= log.id %>">
				<td><%= log.id %></td>
				<td>
					<%= link_to log.logfile.file.filename, log_path(log) %>
					<br /><%= render :partial => 'logs/loglabels', :locals => { :labels => log.labels } %>
				</td>
				<td><%= number_to_human_size(log.logfile.size) %></td>
				<td>
					<div class="btn-group">
						<%= link_to raw('<i class="icon-wrench"></i>'), resources_log_path(log), :remote=>true, :title => 'Log resources', :class => "btn btn-small btn-link" %>
						<%= link_to raw('<i class="icon-pencil"></i>'), edit_log_path(log), :remote => true, :title => 'Edit log', :class => "btn btn-small btn-link" %>
						<%= link_to raw('<i class="icon-trash"></i>'), log, :method => 'delete', :confirm => 'Are you sure you want to delete this log? This cannot be undone.', :title => 'Delete log', :class => "btn btn-small btn-link" %>
					</div>					
				</td>
			</tr>
		<% end %>
	<% end %>
	</tbody>
</table>

app/views/logs/_resources.html.erb
<div class="modal-header">          
  <h3>Log Resources <small><%= @log.logfile.file.filename %></small></h3>       
</div>
<div class="modal-body">
	<table class="table table-striped table-hover table-condensed">
		<thead>
			<tr>
				<th>Resource</th>
				<th width="18%">Hits</th>
			</tr>
		</thead>
		<tbody>
		<% if @resource_matches.size < 1 %>
			<tr>
				<td colspan="4">There were no resources found for this log.</td>
			</tr>
		<% else %>

			<% @resource_matches.each do |key, match| %>
				<tr id="match_<%= match[:resource].id %>">
					<td><%= link_to match[:resource].name, match[:resource].url, :target => "_blank" %></td>
					<td><span class="badge badge-info"><%= match[:hits] %></span></td>
				</tr>
			<% end %>
		<% end %>
		</tbody>
	</table>
</div>

app/views/logs/edit.html.erb
<%= render 'form' %>
<script>
    $("#labels").tagsManager({
        prefilled: <%= @log.labels.map(&:name).to_json.html_safe %>,
        hiddenTagListName: "hiddenTagList",
        typeahead: true,
        typeaheadAjaxSource: '<%= get_names_labels_path :format => "json" %>'
    });
</script>

app/views/logs/edit.js.erb
var inlineLogFormModal = $('<div class="modal hide" id="inlineLogFormModal"></div>');
inlineLogFormModal.html("<%= escape_javascript(render :partial => 'logs/form', :locals => { :inline => true }) %>");

$(".modal-header", inlineLogFormModal).prepend('<button type="button" class="close" data-dismiss="modal">×</button>');

inlineLogFormModal.modal('show');

$("#labels", inlineLogFormModal).tagsManager({
    prefilled: <%= @log.labels.map(&:name).to_json.html_safe %>,
    hiddenTagListName: "hiddenTagList",
    typeahead: true,
    typeaheadAjaxSource: '<%= get_names_labels_path :format => "json" %>'
});

app/views/logs/index.html.erb
<div class="btn-group pull-right span2">
	<%= link_to 'add new log', new_log_path, :remote => true, :title => 'Add new log', :class => "log-modal-toggler btn btn-primary btn-small" %>
</div>

<div class="page-header">	  	
  	<h1>Available Logs</h1> 
</div>	

<div class="row">
	<div class="span12">		
		<%= render 'loglisting' %>
	</div>
</div>

app/views/logs/new.html.erb
<%= render 'form' %>
<script>
    $("#labels").tagsManager({
        hiddenTagListName: "hiddenTagList",
        typeahead: true,
        typeaheadAjaxSource: '<%= get_names_labels_path :format => "json" %>'
    });
</script>

app/views/logs/new.js.erb
var inlineLogFormModal = $('<div class="modal hide" id="inlineLogFormModal"></div>');
inlineLogFormModal.html("<%= escape_javascript(render :partial => 'logs/form') %>");

$(".modal-header", inlineLogFormModal).prepend('<button type="button" class="close" data-dismiss="modal">×</button>');

inlineLogFormModal.modal('show');

$("#labels", inlineLogFormModal).tagsManager({
    hiddenTagListName: "hiddenTagList",
    typeahead: true,
    typeaheadAjaxSource: '<%= get_names_labels_path :format => "json" %>'
});

app/views/logs/resources.html.erb
<div class="btn-group pull-right span3">
	<%= link_to raw('<i class="icon-eye-open"></i> view log'), log_path(@log), :title => 'View log', :class => "modal-toggler btn btn-small" %>
</div>

<%= render 'resources' %>

app/views/logs/resources.js.erb
var inlineLogResourcesModal = $('<div class="modal hide" id="inlineLogResourcesModal"></div>');
inlineLogResourcesModal.html("<%= escape_javascript(render :partial => 'logs/resources') %>");

$(".modal-header", inlineLogResourcesModal).prepend('<button type="button" class="close" data-dismiss="modal">×</button>');
$(".modal-body", inlineLogResourcesModal).after('<div class="modal-footer"><a href="<%= log_path(@log) %>" class="btn btn-primary pull-left">View log</a><a href="<%= resources_log_path(@log) %>" class="btn pull-left"><i class="icon icon-share"></i> Resources permalink</a><a href="<%= log_path(@log) %>" class="btn pull-left" data-dismiss="modal">Close</a></div>');

inlineLogResourcesModal.modal('show');

app/views/logs/show.html.erb
<div class="btn-group pull-right span4">
		<a href="#" id="log-popover-toggler" class="btn btn-small" title="Log Information"><i class="icon-info-sign"></i> log info</a>
		<a href="#" id="cache-popover-toggler" class="btn btn-small" title="Cache Information"><i class="icon-hdd"></i> cache info</a>
		<%= link_to raw('<i class="icon-wrench"></i> resources'), resources_log_path(@log), :title => 'View resources', :class => "modal-toggler btn btn-small", :id => "resources-modal-toggler" %>
		<%= link_to raw('<i class="icon-pencil"></i> edit'), edit_log_path(@log), :remote => true, :title => 'Edit log', :class => "modal-toggler btn btn-small" %>
	</div>

<div class="page-header">	  	
  	<h1>Log Details <small><%= @log.logfile.file.filename %></small></h1> 	
  	<%= render :partial => 'logs/loglabels', :locals => { :labels => @log.labels } %>
</div>

<div id="output">
	<div class="control-group">
    	<div class="controls">			
		<% if @entries[:json_hash]['type'].match(/catalina/i) %>
			<label class="checkbox inline">
				<input class="level-filter" type="checkbox" checked="checked" name="level[]" id="level1" value="SEVERE"> SEVERE
			</label>
			<label class="checkbox inline">
				<input class="level-filter" type="checkbox" name="level[]" id="level3" value="INFO"> INFO
			</label>
		<% else %>
			<label class="checkbox inline">
				<input class="level-filter" type="checkbox" checked="checked" name="level[]" id="level1" value="ERROR"> ERROR
			</label>
			<label class="checkbox inline">
				<input class="level-filter" type="checkbox" name="level[]" id="level2" value="WARN"> WARN
			</label>
			<label class="checkbox inline">
				<input class="level-filter" type="checkbox" name="level[]" id="level3" value="DEBUG"> DEBUG
			</label>
			<label class="checkbox inline">
				<input class="level-filter" type="checkbox" name="level[]" id="level3" value="INFO"> INFO
			</label>
		<% end %>
		</div>
	</div>
	<table id="entries" class="table table-striped table-bordered table-condensed">
		<thead>
			<tr>
				<th style="width:10%">Level</th>
				<th style="width:25%">Class</th>
				<th>Message</th>
				<th style="width:5%">Hits</th>
			</tr>
		</thead>
		<tbody>
		</tbody>
	</table>
</div>

<div class="modal hide" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="TraceModal" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="TraceModal">Stack Trace</h3>
	</div>
	<div class="modal-body"></div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
	</div>
</div>

<div class="modal hide" id="inlineLogResourcesModal">
	<%= render 'resources' %>
	<div class="modal-footer">
		<a href="<%= resources_log_path(@log) %>" class="btn pull-left"><i class="icon icon-share"></i> Resources permalink</a>
		<a href="<%= log_path(@log) %>" class="btn pull-left" data-dismiss="modal">Close</a>
	</div>
</div>

<div id="log-popover-content" class="hide">
	<dl class="dl-horizontal left-align">
		<dt>Type</dt>
		<dd><%= @entries[:json_hash]["type"] %></dd>
		<dt>Size</dt>
		<dd><%= number_to_human_size(@log.logfile.size) %></dd>
		<dt>Lines</dt>
		<dd><%= number_with_delimiter(@entries[:json_hash]["line_total"]) %></dd>
		<dt>Entries Found</dt>
		<dd><%= number_with_delimiter(@entries[:json_hash]["entries"].size) %></dt>
		<dt>Last Updated</dt>
		<dd><%=distance_of_time_in_words(Time.at(@log.updated_at), Time.now)%> ago</dd>
	</dl>
	<%= link_to raw('<i class="icon-white icon-download"></i> Download Log'), download_log_path(@log), :title => 'download log', :class => "btn btn-block btn-primary" %>
</div>
<div id="cache-popover-content" class="hide">
	<dl class="dl-horizontal left-align">
		<dt>Cache File Size</dt>
		<dd><%= number_to_human_size(@log.entriesjson.size) %></dd>
	</dl>
	<%= link_to raw('<i class="icon-white icon-eye-open"></i> View Cache'), log_path(@log, :format => "json"), :class => "btn btn-block btn-primary" %>
</div>

<script>

jQuery.ajaxSetup({ 
  'beforeSend': function(xhr) {
  	xhr.setRequestHeader("Accept", "text/javascript");
  }
})

var LogMaster = {
	self: this,
	log: {},
	entriesTable: null,
	levelMapping: {
		debug: "default",
		info: "info",
		warn: "warning",
		error: "important",
		severe: "important"
	},
	populateDataTable: function(data) {
		var self = this;

		// Redraw the DataTable with the entry data.
		self.entriesTable.dataTable({
			bDestroy: true,
			bAutoWidth: false,
			aaData: data,
			aaSorting: [],
			aoColumns: [
				{ 
					mData: "level",
					fnRender: function ( o, val ) {		        		
						return '<span class="badge badge-'+self.levelMapping[val.toLowerCase()]+' level-badge">' + val + '</span>';
					}
				},
		    { mData: "class" },
		    { 
        	mData: "shortmessage",
        	sClass: "trace-toggle modal-toggler" ,
        	sType: "html",
        	fnRender: function ( o, val ) {
        		if (o.aData.trace !== "") {
    					return '<a href="#" title="View Stack Trace" data-rel="' + o.aData.checksum + '"><i class="icon-tasks"></i></a> <span class="entry-message">' + val + '</span><div style="display:none"><pre>' + o.aData.trace + '</pre></div>'; 
    				} else {
    					return '<span class="entry-message">' + val + '</span>';
    				}        				
    			}
    		},
        { 
        	mData: "hits",
        	sClass: "popover-toggle" ,
        	sSortDataType: "hit-count",
        	sType: "numeric",
        	fnRender: function ( o, val ) {
        		if (o.aData.timestamp.length > 0) {
        			var popoverContent = "",
        				limit = o.aData.timestamp.length < 10 ? o.aData.timestamp.length : 10;
        			for (var i = 0; i < limit; i++) {
        				popoverContent += (o.aData.timestamp[i] + "<br />");
        			}

        			if (o.aData.timestamp.length > limit) {
        				popoverContent += "...";	
        			}

    					return '<a href="#" class="badge badge-info timestamp-badge" title="Timestamps" rel="popover" data-content="'+popoverContent+'"><i class="icon-white icon-time"></i> ' + val + '</a>'; 
    				} else {
    					return '<span class="badge badge-info timestamp-badge">' + val + '</span>';
    				}        				
    			}
        }
		  ],
	    fnDrawCallback: function(o) {
	    	// Add the popovers.
				$("a[rel=popover]").popover({placement: "left"});
	    }
		}).fnFilter("<%= @entries[:json_hash]['type'].match(/catalina/i) ? 'SEVERE' : 'ERROR'%>", 0);
	},
	filterDataTable: function() {
		var self = this,
				regex = '',
				filters = $('.level-filter:checked');

		filters.each(function(i){
			regex += $(this).val() + '|';
		});

		regex = regex.substr(0, regex.length-1)

		// Redraw the DataTable with the filter.
		self.entriesTable.dataTable().fnFilter(regex,0,true);
	}
};

$(document).ready(function(){
	/* Create an array with the values of all the badge values in the hits column */
	$.fn.dataTableExt.afnSortData['hit-count'] = function(oSettings, iColumn) {
		var aData = [];
		$('td:eq('+iColumn+') .badge', oSettings.oApi._fnGetTrNodes(oSettings)).each(function() {
			aData.push(this.text);
		});
		return aData;
	}

	var messageModal = $("#messageModal").modal({show:false}),
			inlineLogResourcesModal = $('#inlineLogResourcesModal').modal({show:false}),
			activePopover = null,
			closeActivePopover = function(){
				// Hide any active popovers.
		    if (activePopover !== null) {
					activePopover.popover('hide');
				}
			};

	// Add a close button to the resources modal.
	$(".modal-header", inlineLogResourcesModal).prepend('<button type="button" class="close" data-dismiss="modal">×</button>');

	LogMaster.entriesTable = $('#entries');
	LogMaster.entriesTable.dataTable({ bSort: false });

	LogMaster.log = <%= @entries[:data].force_encoding("UTF-8").html_safe %>;

	LogMaster.populateDataTable(LogMaster.log.entries);

	// Add a filter event to the entry level checkboxes.
	$('.level-filter').change(function(){
		LogMaster.filterDataTable();
	});

	// Add a click event for the entry trace modal.
	$('td.trace-toggle:has(a)', $('#entries')).live('click', function () {
    $('.modal-body', messageModal).html($('div', $(this)).html());
		messageModal.modal('show');
		return false;   
  });

	// Remove clicking from the popover links
	$("a[rel=popover]").live("click", function(e) {
		e.preventDefault()
	});

	// Create popovers on the fly and toggle them.
	$('a[id$="popover-toggler"]').click(function(e){	
		e.preventDefault();

		var element = $(this),
			elementId = element.attr('id'),
			popoverTitle = element.attr('title'),
			popoverContent = $('#' + elementId.replace('toggler', 'content')).html();

		// Toggle selected popover.	
		element.popover({
			title: popoverTitle,
			content: popoverContent,
			placement: 'bottom',
			trigger: 'manual'
		}).popover('toggle');

		// Clear open popover.
		// Only necessary if the current differs from active.
		if (activePopover !== null && elementId !== activePopover.attr('id')) {
			closeActivePopover()
		}
		
		// Update the active popover.
		activePopover = element;
	});

	// Create a click event for the resources modal.
	$('#resources-modal-toggler').click(function(){
		inlineLogResourcesModal.modal('show');
	});

	// Hide the active popover if a modal's link is clicked.
	$('.modal-toggler').on('click', function(e) {
		e.preventDefault();
		closeActivePopover();
	});
});

</script>