config/routes.rb
Logmaster5000::Application.routes.draw do
  root :to => 'Sessions#new'

  post 'sessions/new'

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  resources :labels do
    collection do
      get :get_names
    end
  end

  resources :logs do
    member do
      get :download
      get :resources
    end
  end

  resources :resources

end

app/views/layouts/_flashmessage.html.erb
<% if flash[:notice].is_a?(Hash) %>
    <div class="alert alert-block alert-<%=flash[:notice][:type]%>">
        <button type="button" class="close" data-dismiss="alert">×</button><%
            case flash[:notice][:type]
                when "error"
                    %><h4>Oops!</h4><%
                when "success"
                    %><h4>Success!</h4><%
            end
        %>
      	<p><%= raw(flash[:notice][:message]) %></p>
        <% if flash[:notice][:issues] && flash[:notice][:issues][:messages].count > 0 %>
            <p><%= pluralize(flash[:notice][:issues][:messages].count, flash[:notice][:issues][:type]) %> encountered:</p>

            <ul>
            <% flash[:notice][:issues][:messages].each do |msg| %>
                <li><%= raw(msg) %></li>
            <% end %>
            </ul>
        <% end %>
      </div>
<% else %>
      <div class="alert alert-block">      			
            <button type="button" class="close" data-dismiss="alert">×</button>
      	<%= flash[:notice] %>
      </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Logmaster5000</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>  
  <%= stylesheet_link_tag    "/javascripts/datatables/css/jquery.dataTables.css", :media => "all" %>  
  

  <%= javascript_include_tag "application", "/javascripts/datatables/js/jquery.dataTables.min.js"  %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top navbar-inverse">
	  <div class="navbar-inner">
	  	<div class="container-fluid">
	  		<%= link_to "LogMaster5000.2", logs_path, :class => "brand" %>
	    	<ul class="nav">
	      		<li><%= link_to "Home", logs_path %></li>
	      		<li><%= link_to "Labels", labels_path %></li>
	      		<li><%= link_to "Resources", resources_path %></li>
	      	</ul>
			<ul class="nav pull-right">
			<% if session[:user_id] %>
				<% user = User.find session[:user_id] %> 
				<li style="padding:10px 15px 10px;">Welcome, <%= user.nickname %></li>
				<li class="divider-vertical"></li>
				<li><a href="<%= logout_path %>">Logout</a></li>
			<% else %>
				<li><a href="<%= login_path %>">Login</a></li>
			<% end %>
			</ul>
		</div>
	  </div>
	</div>
	<div class="container-fluid">
		<% if flash[:notice] %>
			<%= render :partial => "layouts/flashmessage", :locals => { :flash => flash } %>
		<% end %>
		<%= yield %>
	</div>
</html>